import type { MapServicePoint, MapServiceType } from "./map.schemas";

type CuratedMapPoint = Omit<
  MapServicePoint,
  "distanceKm" | "sourceId" | "createdAt" | "bookingUrl" | "profileUrl"
> & {
  sourceId: string;
  bookingUrl?: string | null;
  profileUrl?: string | null;
  createdAt?: string;
};

export const CURATED_MAP_POINTS: CuratedMapPoint[] = [
  {
    id: "grooming_providencia",
    sourceId: "curated_grooming_providencia",
    type: "GROOMING",
    name: "Can Spa Providencia",
    subtitle: "Peluqueria canina especializada",
    description: "Bano, corte por raza y limpieza dental cosmetica.",
    latitude: -33.4312,
    longitude: -70.6159,
    address: "Av. Nueva Providencia 1820",
    city: "Santiago",
    district: "Providencia",
    phone: "+56911112222",
    imageUrl: "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7",
    services: ["Bano", "Corte", "Higiene dental", "Spa premium"],
    openingHours: ["Lun-Vie 09:00-20:00", "Sab 10:00-18:00"],
    priceInfo: ["Desde $18.000", "Pack premium $29.000"],
    priceFrom: 18000,
    hasDiscount: true,
    discountLabel: "15% en primer servicio",
    isEmergency24x7: false,
    isOpenNow: null,
    medicalPriority: false,
    supportsAtHome: false,
    isFeatured: true,
    rating: 4.8,
    reviewsCount: 214
  },
  {
    id: "grooming_las_condes_movil",
    sourceId: "curated_grooming_las_condes_movil",
    type: "GROOMING",
    name: "Grooming Movil Las Condes",
    subtitle: "Atencion a domicilio",
    description: "Unidad movil para bano, corte y limpieza en tu domicilio.",
    latitude: -33.4038,
    longitude: -70.5613,
    address: "Paul Harris 1200",
    city: "Santiago",
    district: "Las Condes",
    phone: "+56933334444",
    imageUrl: "https://images.unsplash.com/photo-1534361960057-19889db9621e",
    services: ["Bano", "Corte", "Deslanado", "Servicio a domicilio"],
    openingHours: ["Lun-Sab 08:30-19:30"],
    priceInfo: ["Desde $21.000", "Traslado incluido"],
    priceFrom: 21000,
    hasDiscount: false,
    discountLabel: null,
    isEmergency24x7: false,
    isOpenNow: null,
    medicalPriority: false,
    supportsAtHome: true,
    isFeatured: false,
    rating: 4.7,
    reviewsCount: 89
  },
  {
    id: "hotel_vitacura_pet",
    sourceId: "curated_hotel_vitacura_pet",
    type: "HOTEL",
    name: "Hotel Perruno Vitacura",
    subtitle: "Hotel y guarderia premium",
    description: "Guarderia diurna, hotel nocturno y camaras en vivo.",
    latitude: -33.3811,
    longitude: -70.573,
    address: "Av. Vitacura 4875",
    city: "Santiago",
    district: "Vitacura",
    phone: "+56955556666",
    imageUrl: "https://images.unsplash.com/photo-1450778869180-41d0601e046e",
    services: ["Hotel", "Guarderia", "Paseos", "Camara en vivo"],
    openingHours: ["Lun-Dom 07:00-23:00"],
    priceInfo: ["Desde $32.000", "Noche + guarderia"],
    priceFrom: 32000,
    hasDiscount: true,
    discountLabel: "10% por estadia semanal",
    isEmergency24x7: false,
    isOpenNow: null,
    medicalPriority: false,
    supportsAtHome: false,
    isFeatured: true,
    rating: 4.9,
    reviewsCount: 167
  },
  {
    id: "hotel_nunoa_patitas",
    sourceId: "curated_hotel_nunoa_patitas",
    type: "HOTEL",
    name: "Guarderia Patitas Nunoa",
    subtitle: "Hotel de mascotas por dia y noche",
    description: "Cuidado para perros y gatos con monitoreo veterinario.",
    latitude: -33.4568,
    longitude: -70.5944,
    address: "Irarrazaval 4050",
    city: "Santiago",
    district: "Nunoa",
    phone: "+56977778888",
    imageUrl: "https://images.unsplash.com/photo-1548767797-d8c844163c4c",
    services: ["Hotel", "Guarderia", "Administracion de medicamentos"],
    openingHours: ["Lun-Sab 08:00-22:00", "Dom 09:00-20:00"],
    priceInfo: ["Desde $27.000"],
    priceFrom: 27000,
    hasDiscount: false,
    discountLabel: null,
    isEmergency24x7: false,
    isOpenNow: null,
    medicalPriority: false,
    supportsAtHome: false,
    isFeatured: false,
    rating: 4.6,
    reviewsCount: 96
  },
  {
    id: "park_bicentenario_pet",
    sourceId: "curated_park_bicentenario_pet",
    type: "PARK",
    name: "Parque Bicentenario Pet Zone",
    subtitle: "Zona pet-friendly con bebederos",
    description: "Parque con sector de juegos para mascotas y zonas de sombra.",
    latitude: -33.3942,
    longitude: -70.6016,
    address: "Av. Bicentenario 3236",
    city: "Santiago",
    district: "Vitacura",
    phone: null,
    imageUrl: "https://images.unsplash.com/photo-1507146426996-ef05306b995a",
    services: ["Parque", "Zona de juegos", "Pet-friendly"],
    openingHours: ["Lun-Dom 06:00-22:00"],
    priceInfo: ["Entrada liberada"],
    priceFrom: 0,
    hasDiscount: false,
    discountLabel: null,
    isEmergency24x7: false,
    isOpenNow: null,
    medicalPriority: false,
    supportsAtHome: false,
    isFeatured: true,
    rating: 4.8,
    reviewsCount: 1203
  },
  {
    id: "park_bustamante_canino",
    sourceId: "curated_park_bustamante_canino",
    type: "PARK",
    name: "Parque Bustamante Canino",
    subtitle: "Area de socializacion para mascotas",
    description: "Espacio abierto para paseos, encuentros y actividades comunitarias.",
    latitude: -33.4438,
    longitude: -70.6295,
    address: "Parque Bustamante, sector sur",
    city: "Santiago",
    district: "Providencia",
    phone: null,
    imageUrl: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b",
    services: ["Parque", "Encuentros", "Pet-friendly"],
    openingHours: ["Lun-Dom 06:30-22:30"],
    priceInfo: ["Entrada liberada"],
    priceFrom: 0,
    hasDiscount: false,
    discountLabel: null,
    isEmergency24x7: false,
    isOpenNow: null,
    medicalPriority: false,
    supportsAtHome: false,
    isFeatured: false,
    rating: 4.5,
    reviewsCount: 845
  }
];

const TYPE_LABELS: Record<MapServiceType, string> = {
  VET: "Veterinaria",
  CAREGIVER: "Cuidador",
  SHOP: "Pet shop",
  GROOMING: "Peluqueria",
  HOTEL: "Hotel / Guarderia",
  PARK: "Parque pet-friendly",
  LOST_PET: "Mascota perdida"
};

export function mapTypeLabel(type: MapServiceType): string {
  return TYPE_LABELS[type];
}
